# Generated by Django 5.0.7 on 2024-07-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
